# Generated by Django 4.0 on 2021-12-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemneed',
            name='brand_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='petapp.itembrand'),
        ),
        migrations.AddField(
            model_name='itemneed',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='itemneed',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='petapp.itemtype'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
